# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wangwenhai\workspace\iothub-device-inspect-tool\addsubscribedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddSubscribeDialog(object):
    def setupUi(self, AddSubscribeDialog):
        AddSubscribeDialog.setObjectName("AddSubscribeDialog")
        AddSubscribeDialog.resize(361, 132)
        AddSubscribeDialog.setSizeGripEnabled(False)
        self.gridLayoutWidget = QtWidgets.QWidget(AddSubscribeDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 20, 311, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.topicEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.topicEdit.setObjectName("topicEdit")
        self.gridLayout.addWidget(self.topicEdit, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.qosSpin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.qosSpin.setMaximum(2)
        self.qosSpin.setObjectName("qosSpin")
        self.gridLayout.addWidget(self.qosSpin, 1, 1, 1, 1)
        self.ensureSubscribeButton = QtWidgets.QPushButton(AddSubscribeDialog)
        self.ensureSubscribeButton.setGeometry(QtCore.QRect(220, 80, 131, 31))
        self.ensureSubscribeButton.setObjectName("ensureSubscribeButton")

        self.retranslateUi(AddSubscribeDialog)
        QtCore.QMetaObject.connectSlotsByName(AddSubscribeDialog)

    def retranslateUi(self, AddSubscribeDialog):
        _translate = QtCore.QCoreApplication.translate
        AddSubscribeDialog.setWindowTitle(_translate("AddSubscribeDialog", "SubscribeTopic"))
        self.label.setText(_translate("AddSubscribeDialog", "Topic"))
        self.label_2.setText(_translate("AddSubscribeDialog", "QOS"))
        self.ensureSubscribeButton.setText(_translate("AddSubscribeDialog", "Ensure Subscribe"))
