# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wangwenhai\workspace\iothub-device-inspect-tool\mqttwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MqttWindow(object):
    def setupUi(self, MqttWindow):
        MqttWindow.setObjectName("MqttWindow")
        MqttWindow.resize(958, 620)
        self.centralwidget = QtWidgets.QWidget(MqttWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 941, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.connectButton.setStyleSheet("")
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 3, 4, 1, 1)
        self.usernameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.usernameEdit.setObjectName("usernameEdit")
        self.gridLayout.addWidget(self.usernameEdit, 1, 1, 1, 4)
        self.passwordEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridLayout.addWidget(self.passwordEdit, 2, 1, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.clientIdEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.clientIdEdit.setObjectName("clientIdEdit")
        self.gridLayout.addWidget(self.clientIdEdit, 0, 1, 1, 4)
        self.hostEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hostEdit.setObjectName("hostEdit")
        self.gridLayout.addWidget(self.hostEdit, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.portSpin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.portSpin.setMinimum(1)
        self.portSpin.setMaximum(65535)
        self.portSpin.setProperty("value", 1883)
        self.portSpin.setObjectName("portSpin")
        self.gridLayout.addWidget(self.portSpin, 3, 3, 1, 1)
        self.cleanSessionRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.cleanSessionRadio.setAutoFillBackground(True)
        self.cleanSessionRadio.setChecked(True)
        self.cleanSessionRadio.setObjectName("cleanSessionRadio")
        self.gridLayout.addWidget(self.cleanSessionRadio, 3, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 470, 941, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.publishMsgButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.publishMsgButton.setObjectName("publishMsgButton")
        self.gridLayout_2.addWidget(self.publishMsgButton, 3, 3, 1, 1)
        self.publishTopicEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.publishTopicEdit.setObjectName("publishTopicEdit")
        self.gridLayout_2.addWidget(self.publishTopicEdit, 0, 1, 1, 1)
        self.pubMsgEdit = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.pubMsgEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.pubMsgEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.pubMsgEdit.setAcceptRichText(False)
        self.pubMsgEdit.setObjectName("pubMsgEdit")
        self.gridLayout_2.addWidget(self.pubMsgEdit, 2, 1, 2, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.publishQosSpin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.publishQosSpin.setWrapping(True)
        self.publishQosSpin.setReadOnly(False)
        self.publishQosSpin.setMaximum(2)
        self.publishQosSpin.setObjectName("publishQosSpin")
        self.gridLayout_2.addWidget(self.publishQosSpin, 0, 3, 1, 1)
        self.clearContentButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.clearContentButton.setObjectName("clearContentButton")
        self.gridLayout_2.addWidget(self.clearContentButton, 3, 2, 1, 1)
        self.dupCheck = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.dupCheck.setObjectName("dupCheck")
        self.gridLayout_2.addWidget(self.dupCheck, 2, 2, 1, 1)
        self.retainCheck = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.retainCheck.setObjectName("retainCheck")
        self.gridLayout_2.addWidget(self.retainCheck, 2, 3, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 140, 941, 321))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.logTab = QtWidgets.QTabWidget(self.gridLayoutWidget_3)
        self.logTab.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #C2C7CB;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C3;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}")
        self.logTab.setObjectName("logTab")
        self.subscribeTab = QtWidgets.QWidget()
        self.subscribeTab.setObjectName("subscribeTab")
        self.subscribeListView = QtWidgets.QListView(self.subscribeTab)
        self.subscribeListView.setGeometry(QtCore.QRect(0, 40, 861, 251))
        self.subscribeListView.setStyleSheet("QListView {\n"
"    font: 12pt \"Arial\";\n"
"}\n"
"\n"
"QListView::item {\n"
"    background-color: #8CF6FF;\n"
"    color: #000000;\n"
"    border-bottom: 1px solid #dbdbdb;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: #25F4CB;\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    border-left: 5px solid #1BCFAB;\n"
"}\n"
"")
        self.subscribeListView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.subscribeListView.setProperty("isWrapping", False)
        self.subscribeListView.setObjectName("subscribeListView")
        self.addSubscribeButton = QtWidgets.QPushButton(self.subscribeTab)
        self.addSubscribeButton.setGeometry(QtCore.QRect(870, 40, 61, 31))
        self.addSubscribeButton.setObjectName("addSubscribeButton")
        self.deleteSubscribeButton = QtWidgets.QPushButton(self.subscribeTab)
        self.deleteSubscribeButton.setGeometry(QtCore.QRect(870, 80, 61, 31))
        self.deleteSubscribeButton.setObjectName("deleteSubscribeButton")
        self.label_7 = QtWidgets.QLabel(self.subscribeTab)
        self.label_7.setGeometry(QtCore.QRect(0, 10, 101, 20))
        self.label_7.setStyleSheet("font: 10pt \"Arial\";")
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setObjectName("label_7")
        self.logTab.addTab(self.subscribeTab, "")
        self.msgReceivedTab = QtWidgets.QWidget()
        self.msgReceivedTab.setObjectName("msgReceivedTab")
        self.msgTextBrowser = QtWidgets.QTextBrowser(self.msgReceivedTab)
        self.msgTextBrowser.setGeometry(QtCore.QRect(0, 0, 941, 291))
        self.msgTextBrowser.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.msgTextBrowser.setStyleSheet("QTextBrowser\n"
"{\n"
"    show-decoration-selected: 1;\n"
"    color: rgb(85, 255, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-color: rgb(85, 255, 127);\n"
"}")
        self.msgTextBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.msgTextBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.msgTextBrowser.setObjectName("msgTextBrowser")
        self.logTab.addTab(self.msgReceivedTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.logTextBrowser = QtWidgets.QTextBrowser(self.tab)
        self.logTextBrowser.setGeometry(QtCore.QRect(0, 0, 941, 291))
        self.logTextBrowser.setStyleSheet("QTextBrowser\n"
"{\n"
"    show-decoration-selected: 1;\n"
"    color: rgb(85, 255, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-color: rgb(85, 255, 127);\n"
"}")
        self.logTextBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logTextBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logTextBrowser.setObjectName("logTextBrowser")
        self.logTab.addTab(self.tab, "")
        self.gridLayout_3.addWidget(self.logTab, 0, 1, 1, 1)
        MqttWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MqttWindow)
        self.logTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MqttWindow)

    def retranslateUi(self, MqttWindow):
        _translate = QtCore.QCoreApplication.translate
        MqttWindow.setWindowTitle(_translate("MqttWindow", "MQTT Client"))
        self.label.setText(_translate("MqttWindow", "ClientId"))
        self.label_4.setText(_translate("MqttWindow", "Host"))
        self.connectButton.setText(_translate("MqttWindow", "Connect"))
        self.label_3.setText(_translate("MqttWindow", "Password"))
        self.hostEdit.setText(_translate("MqttWindow", "127.0.0.1"))
        self.label_2.setText(_translate("MqttWindow", "Username"))
        self.cleanSessionRadio.setText(_translate("MqttWindow", "Clean Session"))
        self.label_5.setText(_translate("MqttWindow", "Topic"))
        self.publishMsgButton.setText(_translate("MqttWindow", "Send"))
        self.label_8.setText(_translate("MqttWindow", "QOS"))
        self.label_6.setText(_translate("MqttWindow", "Text"))
        self.clearContentButton.setText(_translate("MqttWindow", "Clear"))
        self.dupCheck.setText(_translate("MqttWindow", "Duplicate"))
        self.retainCheck.setText(_translate("MqttWindow", "Retain"))
        self.addSubscribeButton.setText(_translate("MqttWindow", "Add"))
        self.deleteSubscribeButton.setText(_translate("MqttWindow", "Delete"))
        self.label_7.setText(_translate("MqttWindow", "QOS | Topic"))
        self.logTab.setTabText(self.logTab.indexOf(self.subscribeTab), _translate("MqttWindow", "Subscribe"))
        self.msgTextBrowser.setHtml(_translate("MqttWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.logTab.setTabText(self.logTab.indexOf(self.msgReceivedTab), _translate("MqttWindow", "MsgReceived"))
        self.logTab.setTabText(self.logTab.indexOf(self.tab), _translate("MqttWindow", "Log"))
