# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wangwenhai\workspace\iothub-device-inspect-tool\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 364)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 130, 81, 61))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 22))
        self.menubar.setObjectName("menubar")
        self.menu1 = QtWidgets.QMenu(self.menubar)
        self.menu1.setObjectName("menu1")
        self.menu2 = QtWidgets.QMenu(self.menubar)
        self.menu2.setObjectName("menu2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMQTT = QtWidgets.QAction(MainWindow)
        self.actionMQTT.setObjectName("actionMQTT")
        self.actionCOAP = QtWidgets.QAction(MainWindow)
        self.actionCOAP.setObjectName("actionCOAP")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu1.addAction(self.actionMQTT)
        self.menu1.addAction(self.actionCOAP)
        self.menu2.addAction(self.actionAbout)
        self.menubar.addAction(self.menu1.menuAction())
        self.menubar.addAction(self.menu2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IoT Test Tool"))
        self.label.setText(_translate("MainWindow", "IoT Test Tool"))
        self.menu1.setTitle(_translate("MainWindow", "新建"))
        self.menu2.setTitle(_translate("MainWindow", "关于"))
        self.actionMQTT.setText(_translate("MainWindow", "MQTT Client"))
        self.actionCOAP.setText(_translate("MainWindow", "COAP Client"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
